name: Standard Task
description: Use this template for standard tasks
title: "Task title"
labels: ["task"]
projects:
  - sensinno/5

body:
  - type: markdown
    attributes:
      value: |
        # Task Template
        Fill in description so that the assignee can complete the task without additional info, and that any other team member will understand the overall goal. 

  - type: markdown
    attributes:
      value: |
        ## Context
        Please provide the scope, purpose and the most relevant background details of the task.

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Provide a high level overview of the task, making the limitations of the task clear.
      placeholder: The task covers... 
    validations:
      required: false

  - type: textarea
    id: background
    attributes:
      label: Background / Purpose
      description: Provide any additional information or context for this task.
      placeholder: The reason for the task is... 
    validations:
      required: false


  - type: markdown
    attributes:
      value: |
        ## Instructions
        Provide detailed instructions for completing the task.

  - type: textarea
    id: instructions
    attributes:
      label: Instructions
      description: Provide detailed instructions for completing the task.
      placeholder: Steps to complete the task are...
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define the acceptance criteria for this task.
      placeholder: When completed the system/user should be able to...
    validations:
      required: false


  - type: markdown
    attributes:
      value: |
        ## References
        Provide reference screenshots, diagrams or data examples

  - type: textarea
    id: references
    attributes:
      label: References
      description: Attach related issues, reference screenshots, diagrams or data examples.
    validations:
      required: false